// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/api/runTourney.ts";
import * as $2 from "./routes/connect.tsx";
import * as $3 from "./routes/dashboard.tsx";
import * as $4 from "./routes/demo.tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/profile.tsx";
import * as $7 from "./routes/tourney/[id].tsx";
import * as $$0 from "./islands/DemoSelector.tsx";
import * as $$1 from "./islands/GameSelector.tsx";
import * as $$2 from "./islands/Selector.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/api/runTourney.ts": $1,
    "./routes/connect.tsx": $2,
    "./routes/dashboard.tsx": $3,
    "./routes/demo.tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/profile.tsx": $6,
    "./routes/tourney/[id].tsx": $7,
  },
  islands: {
    "./islands/DemoSelector.tsx": $$0,
    "./islands/GameSelector.tsx": $$1,
    "./islands/Selector.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
